/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author user
 */
public class datacustomer extends javax.swing.JFrame {
private Connection conn = koneksi.connect();
    private DefaultTableModel tabmode;
    
    
    
    public datacustomer() {
        initComponents();
        datatable();
        setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) /2,
        (Toolkit.getDefaultToolkit().getScreenSize().height - getHeight())/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataCustomer = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtKdCustomer = new javax.swing.JTextField();
        txtNmCustomer = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextArea();
        lblKdBarang1 = new javax.swing.JLabel();
        lblNmBarang1 = new javax.swing.JLabel();
        lblHarga1 = new javax.swing.JLabel();
        lblJumlah1 = new javax.swing.JLabel();
        btnSegarkan = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        cmdCetak1 = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Stok Obat Klinik Tine - Data Customer");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("../img/icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(232, 241, 251));

        tabelDataCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelDataCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelDataCustomer);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(150, 182, 230));
        jLabel6.setText("Data Customer");

        txtKdCustomer.setEditable(false);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);

        lblKdBarang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblKdBarang1.setForeground(new java.awt.Color(150, 182, 230));
        lblKdBarang1.setText("Kode Customer");

        lblNmBarang1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNmBarang1.setForeground(new java.awt.Color(150, 182, 230));
        lblNmBarang1.setText("Nama Customer");

        lblHarga1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHarga1.setForeground(new java.awt.Color(150, 182, 230));
        lblHarga1.setText("Nomor Telepon");

        lblJumlah1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblJumlah1.setForeground(new java.awt.Color(150, 182, 230));
        lblJumlah1.setText("Alamat");

        btnSegarkan.setBackground(new java.awt.Color(255, 255, 255));
        btnSegarkan.setText("Segarkan");
        btnSegarkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSegarkanActionPerformed(evt);
            }
        });

        btnSimpan.setBackground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnKeluar.setBackground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Kembali");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 255, 255));
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnCari.setBackground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        cmdCetak1.setBackground(new java.awt.Color(255, 255, 255));
        cmdCetak1.setText("Print");
        cmdCetak1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCetak1ActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Buat");
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
        });
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(159, 159, 159))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNmBarang1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblHarga1)
                                    .addComponent(lblJumlah1))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTelepon)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblKdBarang1)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNmCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtKdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnTambah)))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSegarkan)
                            .addGap(18, 18, 18)
                            .addComponent(btnSimpan)
                            .addGap(29, 29, 29)
                            .addComponent(btnUbah)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnKeluar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCari)
                            .addGap(18, 18, 18)
                            .addComponent(cmdCetak1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKdBarang1)
                    .addComponent(txtKdCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNmBarang1)
                    .addComponent(txtNmCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarga1)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJumlah1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnSegarkan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnKeluar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdCetak1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 protected void aktif(){
        txtNmCustomer.setEnabled(true);
        txtAlamat.setEnabled(true);
        txtTelepon.setEnabled(true);
        txtKdCustomer.setEnabled(true);
    }
    protected void kosong(){
        txtKdCustomer.setText("");
        txtNmCustomer.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
        txtKdCustomer.requestFocus();
    }
    private void no_supplier(){
        try {
            java.sql.Statement stat = conn.createStatement();
            String sql = "select * from datasupplier order by kd_supp desc";
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                String kd_supp = hasil.getString("kd_supp").substring(3);
                String AN = "" +(Integer.parseInt(kd_supp)+1);
                String Nol = "";
                if(AN.length()==1)
                {Nol="00";}
                else if(AN.length()==2)
                {Nol="0";}
                else if(AN.length()==3)
                {Nol="";}
                txtKdCustomer.setText("Customer"+Nol+AN);
            }else{
                txtKdCustomer.setText("Customer001");
                   }
            hasil.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    protected void datatable(){
        Object[] Baris={"Kode Customer","Nama Customer","No. Telepon","Alamat"};
        tabmode = new DefaultTableModel(null,Baris);
        tabelDataCustomer.setModel(tabmode);
        String sql = "select * from datacustomer";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String kd_cust = hasil.getString("kd_cust");
                String nm_cust = hasil.getString("nm_cust");
                String no_tlp = hasil.getString("no_tlp");
                String alamat = hasil.getString("alamat");
                String[] data = {kd_cust,nm_cust,no_tlp,alamat};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
        }
    }
    private void no_customer(){
        
        try {
            java.sql.Statement stat = conn.createStatement();
            String sql = "select * from datacustomer order by kd_cust desc";
            ResultSet hasil = stat.executeQuery(sql);
            if(hasil.next()){
                String kd_cust = hasil.getString("kd_cust").substring(2);
                String AN = "" +(Integer.parseInt(kd_cust)+1);
                String Nol = "";
                if(AN.length()==1)
                {Nol="00";}
                else if(AN.length()==2)
                {Nol="0";}
                else if(AN.length()==3)
                {Nol="";}
                txtKdCustomer.setText("CU"+Nol+AN);
            }else{
                txtKdCustomer.setText("CU001");
                   }
            hasil.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void cari() {
         Object header[] = {"Kode Customer","Nama Customer","No. Telepon","Alamat"};
        tabmode = new DefaultTableModel(null, header);
        tabelDataCustomer.setModel(tabmode);

        int baris = tabelDataCustomer.getRowCount();
        for (int i = 0; i < baris; i++) {
            tabmode.removeRow(i);
        }

        String sql_select = "select * from datacustomer where kd_cust like '%"+txtCari.getText()
                +"%' or nm_cust like '%"+txtCari.getText()+"%'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet rs = stat.executeQuery(sql_select);
            while (rs.next()) {
                String kd_cust = rs.getString("kd_cust");
                String nm_cust = rs.getString("nm_cust");
                String no_tlp = rs.getString("no_tlp");
		String alamat = rs.getString("alamat");
                String[] kolom = {kd_cust,nm_cust,no_tlp,alamat};
                tabmode.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    private void tabelDataCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataCustomerMouseClicked
         int bar = tabelDataCustomer.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        
        txtKdCustomer.setText(a);
        txtNmCustomer.setText(b);
        txtTelepon.setText(c);
        txtAlamat.setText(d);
    }//GEN-LAST:event_tabelDataCustomerMouseClicked

    
    
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String sql = "insert into datacustomer values (?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtKdCustomer.getText());
            stat.setString(2, txtNmCustomer.getText());
            stat.setString(3, txtTelepon.getText());
            stat.setString(4, txtAlamat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diSimpan");
            kosong();
            txtKdCustomer.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal disimpan"+e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
         int ex= JOptionPane.showConfirmDialog(null,"Apakah Anda akan keluar? ","Anda yakin?",
            JOptionPane.YES_NO_OPTION);
        if(ex==0)
        {
            new menuutama().setVisible(true); 
                    dispose();
}
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String sql = "delete from datacustomer where kd_cust='"+txtKdCustomer.getText()+"'";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            int sukses = stat.executeUpdate();
            if(sukses>0){
                JOptionPane.showMessageDialog(null, "Data berhasil diHapus");
                kosong();
                txtKdCustomer.requestFocus();
                datatable();
            }else{
                JOptionPane.showMessageDialog(null, "Data Gagal dihapus");
            }
            conn.close();
            stat.close();
        }catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String sql = "update datacustomer set nm_cust=?,no_tlp=?,alamat=? where kd_cust='"+txtKdCustomer.getText()+"'";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtNmCustomer.getText());
            stat.setString(2, txtTelepon.getText());
            stat.setString(3, txtAlamat.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil diSimpan");
            kosong();
            txtKdCustomer.requestFocus();
            datatable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Data Gagal disimpan"+e);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        cari();
    }//GEN-LAST:event_btnCariActionPerformed

    private void cmdCetak1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCetak1ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Data Table Customer");
        MessageFormat footer = new MessageFormat("page (0, number,integer)");
        try {
            tabelDataCustomer.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        } catch(java.awt.print.PrinterException e) {
            System.err.format("tidak bisa di pritn",e.getMessage());
        }
    }//GEN-LAST:event_cmdCetak1ActionPerformed

    private void btnSegarkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSegarkanActionPerformed
        datatable();
    }//GEN-LAST:event_btnSegarkanActionPerformed

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        no_customer();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datacustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datacustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datacustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datacustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new datacustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnSegarkan;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton cmdCetak1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga1;
    private javax.swing.JLabel lblJumlah1;
    private javax.swing.JLabel lblKdBarang1;
    private javax.swing.JLabel lblNmBarang1;
    private javax.swing.JTable tabelDataCustomer;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtKdCustomer;
    private javax.swing.JTextField txtNmCustomer;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
