/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilan;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author user
 */

public class menuutama extends javax.swing.JFrame {
 tampilan.UserSession userSession = new tampilan.UserSession();

    /**
     * Creates new form menuutama
     */
    public menuutama() { 
    initComponents();
     //setLocationRelativeTo(null);      

        
    //userLogin();
    //hakakses();
    setTanggal();
    setJam(); 
    setLocation((Toolkit.getDefaultToolkit().getScreenSize().width - getWidth()) /2,
    (Toolkit.getDefaultToolkit().getScreenSize().height - getHeight())/2);
    }

    

    
    public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd-MM-yyyy");
    Tanggal.setText(kal.format(skrg));
    } 
 
    public void setJam(){
      ActionListener taskPerformer = new ActionListener() {

        public void actionPerformed(ActionEvent evt) {
        String nol_jam = "", nol_menit = "",nol_detik = "";

        java.util.Date dateTime = new java.util.Date();
        int nilai_jam = dateTime.getHours();
                int nilai_menit = dateTime.getMinutes();
                int nilai_detik = dateTime.getSeconds();

                if(nilai_jam <= 9) nol_jam= "0";
                if(nilai_menit <= 9) nol_menit= "0";
                if(nilai_detik <= 9) nol_detik= "0";

                String waktu = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);

            Jam.setText(waktu+":"+menit+":"+detik+"");
        }
        };
        new Timer(1000, taskPerformer).start();
    }    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        Tanggal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblJudul = new javax.swing.JLabel();
        Jam = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MDataCust = new javax.swing.JMenuItem();
        MDataKaryawan = new javax.swing.JMenuItem();
        MDataSupp = new javax.swing.JMenuItem();
        MDataObat = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        TObatMasuk = new javax.swing.JMenuItem();
        TObatKeluar = new javax.swing.JMenuItem();

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Stok Obat Klinik Tine");
        setBackground(new java.awt.Color(232, 241, 251));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("../img/icon.png")).getImage());

        jPanel1.setBackground(new java.awt.Color(232, 241, 251));

        Tanggal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tanggal.setForeground(new java.awt.Color(150, 182, 230));
        Tanggal.setText("Tanggal");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(150, 182, 230));
        jLabel1.setText("Selamat datang");

        lblNama.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblNama.setForeground(new java.awt.Color(150, 182, 230));
        lblNama.setText("nama");

        lblJudul.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblJudul.setForeground(new java.awt.Color(150, 182, 230));
        lblJudul.setText("SISTEM PENDATAAN STOK OBAT KLINIK TINE");

        Jam.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Jam.setForeground(new java.awt.Color(150, 182, 230));
        Jam.setText("jam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblJudul)
                        .addGap(0, 350, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Tanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jam)
                        .addGap(6, 6, 6)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblJudul)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Tanggal)
                            .addComponent(Jam)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblNama))))
                .addContainerGap(317, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(232, 241, 251));
        jMenuBar1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem1.setText("User");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Master");
        jMenu2.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        MDataCust.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MDataCust.setText("Data Customer");
        MDataCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDataCustActionPerformed(evt);
            }
        });
        jMenu2.add(MDataCust);

        MDataKaryawan.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MDataKaryawan.setText("Data Karyawan");
        MDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDataKaryawanActionPerformed(evt);
            }
        });
        jMenu2.add(MDataKaryawan);

        MDataSupp.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MDataSupp.setText("Data Supplier");
        MDataSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDataSuppActionPerformed(evt);
            }
        });
        jMenu2.add(MDataSupp);

        MDataObat.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        MDataObat.setText("Data Obat");
        MDataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MDataObatActionPerformed(evt);
            }
        });
        jMenu2.add(MDataObat);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Transaksi");
        jMenu3.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        TObatMasuk.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TObatMasuk.setText("Transaksi Obat Masuk");
        TObatMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TObatMasukActionPerformed(evt);
            }
        });
        jMenu3.add(TObatMasuk);

        TObatKeluar.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        TObatKeluar.setText("Transaksi Obat Keluar");
        TObatKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TObatKeluarActionPerformed(evt);
            }
        });
        jMenu3.add(TObatKeluar);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        login lg = new login();
        lg.setVisible(true);
        dispose();          // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void MDataSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDataSuppActionPerformed
        datasupplier lg = new datasupplier();
        lg.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MDataSuppActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        datakaryawan lg = new datakaryawan();
        lg.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        datacustomer lg = new datacustomer();
        lg.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void MDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDataKaryawanActionPerformed
        datakaryawan lg = new datakaryawan();
        lg.setVisible(true);
        dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_MDataKaryawanActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        obatkeluar lg = new obatkeluar();
        lg.setVisible(true);
        dispose(); 
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void TObatMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TObatMasukActionPerformed
        obatmasuk lg = new obatmasuk();
        lg.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_TObatMasukActionPerformed

    private void MDataCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDataCustActionPerformed
       datacustomer lg = new datacustomer();
        lg.setVisible(true);
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_MDataCustActionPerformed

    private void TObatKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TObatKeluarActionPerformed
        obatkeluar lg = new obatkeluar();
        lg.setVisible(true);
        dispose();     // TODO add your handling code here:
    }//GEN-LAST:event_TObatKeluarActionPerformed

    private void MDataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MDataObatActionPerformed
        dataobat lg = new dataobat();
        lg.setVisible(true);
        dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_MDataObatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuutama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuutama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jam;
    private javax.swing.JMenuItem MDataCust;
    private javax.swing.JMenuItem MDataKaryawan;
    private javax.swing.JMenuItem MDataObat;
    private javax.swing.JMenuItem MDataSupp;
    private javax.swing.JMenuItem TObatKeluar;
    private javax.swing.JMenuItem TObatMasuk;
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNama;
    // End of variables declaration//GEN-END:variables
}
